sourceTableName: MESSAGE
maximumPoolSize: 10
kafka: kafka:9092
zookeeper: zookeeper:2181
leadershipLockPath: /eventuatelocal/cdc/leader
maxEventsPerPolling: 20
maxAttemptsForPolling: 5
pollingRetryIntervalInMilliseconds: 200
pollingIntervalInMilliseconds: 5000