#
# docker-compose-oracle.yml
#
# Docker compose file for Oracle to support OAUTH and API/microservice
# reference training
#
# Key Considerations:
# - oracle service is on a single external bridge network
#
# Author: Dan Dobrin
#

#
# **** NOTE:  any volumes must be defined relative to this file
#

version: '2'

#
# Services
#
services:

    #
    # Oracle database
    #
  oracle:
       image: wnameless/oracle-xe-11g:16.04
       volumes:
          - ./oracle/config2:/docker-entrypoint-initdb.d
       ports:
          - "1521:1521"
       networks:
          - localnet


  zookeeper:
       build: ./zookeeper/
       ports:
          - 2181:2181
          - 2888:2888
       networks:
          - localnet

  kafka:
       build: ./kafka/
       ports:
          - 9092:9092
       links:
          - zookeeper
       environment:
          - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
          - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
          - ZOOKEEPER_SERVERS=zookeeper:2181
       networks:
          - localnet

#
# Networks
#
networks:
    localnet:
        # driver: bridge
        external: true
