version: "2"
#
# Services
#
services:
  mysql:
    image: networknt/eventuate-mysql:latest
    restart: always
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - localnet

  influxdb:
    image: influxdb:1.3-alpine
    restart: always
    volumes:
      - /opt/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_USER=metrics
      - INFLUXDB_USER_PASSWORD=secret
      - INFLUXDB_DB=metrics
    networks:
      - localnet

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - /opt/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - localnet

  consul:
    image:  gliderlabs/consul:latest
    restart: always
    command: "agent -server -data-dir /tmp/consul -bootstrap -ui -client=0.0.0.0"
    ports:
      - 8500:8500
      - 8400:8400

  # registrator:
    # image: gliderlabs/registrator:latest
    # restart: always
    # command: "consul://consul:8500"
    # network_mode: "host"
    # volumes:
      # - /var/run/docker.sock:/tmp/docker.sock
    # links:
      # - consul

  oauth2-code:
    image: networknt/oauth2-code
    restart: always
    ports:
      - "6881:6881"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-code"
    #    env: "dev"
  oauth2-token:
    image: networknt/oauth2-token
    restart: always
    ports:
      - "6882:6882"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-token"
    #    env: "dev"
  oauth2-service:
    image: networknt/oauth2-service
    restart: always
    ports:
      - "6883:6883"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-service"
    #    env: "dev"
  oauth2-client:
    image: networknt/oauth2-client
    restart: always
    ports:
      - "6884:6884"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-client"
    #    env: "dev"
  oauth2-user:
    image: networknt/oauth2-user
    restart: always
    ports:
      - "6885:6885"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-user"
    #    env: "dev"
  oauth2-key:
    image: networknt/oauth2-key
    restart: always
    ports:
      - "6886:6886"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-key"
    #    env: "dev"
  oauth2-refresh-token:
    image: networknt/oauth2-refresh-token
    restart: always
    ports:
      - "6887:6887"
    volumes:
      - ./light-oauth2/mysql/config:/config
    networks:
      - localnet
    depends_on:
      - mysql
    links:
      - mysql
    #logging:
    #  driver: "gelf"
    #  options:
    #    gelf-address: "udp://localhost:12201"
    #    tag: "oauth2-refresh-token"
    #    env: "dev"

  elasticsearch:
    build: elasticsearch/
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - localnet
  logstash:
    build: logstash/
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - localnet
  kibana:
    build: kibana/
    restart: always
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - localnet

# Networks
#
networks:
  localnet:
    external: true
