version: "2"
#
# As Kafka needs your docker host name or IP, we have to set it in
# environment variable before starting this compose. Note that on
# Linux, you cannot use "./set-docker-host-ip.sh" as the variable
# is set for the child shell and the parent shell doesn't have it.
#
# You should use source instead of running it with another shell.
#
# source set-docker-host-ip.sh
#
services:
  mysql:
     image: networknt/mysql:latest
     ports:
      - 3306:3306
     environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
     networks:
      - localnet

  zookeeper:
       image: networknt/zookeeper:latest
       ports:
          - 2181:2181
          - 2888:2888
       networks:
          - localnet

  kafka:
       image: networknt/kafka:latest
       ports:
          - 9092:9092
       links:
          - zookeeper
       environment:
          - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
          - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
          - ZOOKEEPER_SERVERS=zookeeper:2181
       networks:
          - localnet

  eventuate-cdcserver:
       image: networknt/eventuate-cdcserver:latest
       volumes:
          - ./eventuate-cdcserver/config:/config
       networks:
          - localnet

# Networks
#
networks:
  localnet:
    external: true
