version: "2"
#
# Services
#
services:
  mysql:
       build: ./eventuate-mysql/
       ports:
           - 3306:3306
       environment:
           - MYSQL_ROOT_PASSWORD=rootpassword
           - MYSQL_USER=mysqluser
           - MYSQL_PASSWORD=mysqlpw
       networks:
           - localnet

  zookeeper:
       build: ./eventuate-zookeeper/
       ports:
          - 2181:2181
          - 2888:2888
       networks:
          - localnet

  kafka:
       build: ./eventuate-kafka/
       ports:
          - 9092:9092
       links:
          - zookeeper
       environment:
          - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
          - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
          - ZOOKEEPER_SERVERS=zookeeper:2181
       networks:
          - localnet



# Networks
#
networks:
  localnet:
    external: true
